
"""
state.py
the shared state schema. flows through every node in the
graph. nodes write updates to this structure
"""

from typing import TypedDict, Annotated, List, Dict
import operator
from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages


class AgentState(TypedDict):
    #conversation history saver where addmessage is the reducer, meaning new messages are appended to this list
    messages: Annotated[List[BaseMessage], add_messages] 

    #original research topic set at the start of a run
    topic: str

    #long list of queries & subquestions (generated by planner) by breaking down the topic
    plan: List[str] #read by researcher node

    #for every infomation tools gathered, operator.add is the reducer, meaning new sources are appended to this list
    sources: Annotated[List[Dict], operator.add]

    #count of how many times the Researcher -> Reflect loop has run. reflect node check for infiinite loop
    iteration_count: int

    #boolean to true once reflect gather enough topic (source suffiecient)
    research_complete: bool

    #record tool calls made by the Researcher node, so the Responder node can summarize them in the final answer (accounts for failure) 
    errors: Annotated[List[str], operator.add]

    #final synthesized answer wrote by the Responder node
    final_answer: str